# Generated by Django 4.1.7 on 2024-06-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='joined_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
