# Generated by Django 4.1.7 on 2024-06-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_checker_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
