# Generated by Django 4.1.7 on 2024-06-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_maker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maker',
            name='user',
        ),
    ]
