# Generated by Django 4.1.7 on 2024-06-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_maker_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('qualification', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=6)),
                ('age', models.DateField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(default='pending', max_length=10)),
            ],
        ),
    ]
