# Generated by Django 4.1.7 on 2024-06-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_maker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checker',
            name='approved',
        ),
    ]
