# Generated by Django 4.1.7 on 2024-06-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_checker_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='Log_Action',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
