# Generated by Django 4.1.7 on 2024-06-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_checker_log_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maker',
            old_name='emailid',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='maker',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='maker',
            old_name='lastname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='maker',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='checker',
            name='Log_Action',
        ),
    ]
