# Generated by Django 4.1.7 on 2024-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_checker_password_remove_checker_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checker',
            name='is_maker',
        ),
        migrations.AddField(
            model_name='checker',
            name='is_checker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cutomeruser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cutomeruser',
            name='is_checker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cutomeruser',
            name='is_maker',
            field=models.BooleanField(default=False),
        ),
    ]
