# Generated by Django 4.1.7 on 2024-06-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_remove_checker_is_maker_checker_is_checker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checker',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maker',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maker',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
