# Generated by Django 4.1.7 on 2024-06-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_checker_password_checker_username_maker_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.checker'),
        ),
    ]
